services:
  client:
    build: 
      context: client
      target: dev
    ports:
      - "4200:4200"
    volumes:
      - /client/node_modules
      - ./client/src:/client/src:ro

  server:
    build:
      context: server
      target: dev
    environment:
      ALLOWED_HOSTS: '*'
      DEBUG: '1'
      PGDATABASE: postgres
      PGHOST: /run/postgresql
      PGNAME: postgres
      PGUSER: postgres
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app:ro
      - postgres-sock:/run/postgresql

  db:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: "pg_isready -U postgres || exit 1"
      retries: 10
    command: -c listen_addresses=''
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - postgres-sock:/run/postgresql

  redisearch:
    image: redislabs/redisearch:1.6.13
    healthcheck:
      test: "redis-cli ping"

  chado_to_redisearch:
    build: search/database 
    depends_on:
      db:
        condition: service_healthy
      redisearch:
        condition: service_healthy
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST: /run/postgresql
      REDIS_HOST: redisearch
    command:
      - --no-reload
    volumes:
      - postgres-sock:/run/postgresql

  gene_search:
    build: search/microservices/gene_search
    depends_on:
      - chado_to_redisearch
    environment:
      REDIS_HOST: redisearch
    expose:
      - "8081"
    command:
      - --no-http


  chromosome_search:
    build: search/microservices/chromosome_search
    depends_on:
      - chado_to_redisearch
    environment:
      REDIS_HOST: redisearch
      GRPC_HOST: "0.0.0.0"
    expose:
      - "8081"
    command:
      - --no-http


  chromosome_region:
    build: search/microservices/chromosome_region
    depends_on:
      - chado_to_redisearch
    environment:
      HTTP_HOST: "0.0.0.0"
      REDIS_HOST: redisearch
      GRPC_HOST: "0.0.0.0"
    ports:
      - "8083:8080"
    expose:
      - "8080"
      - "8081"

  search:
    build: search/microservices/search
    depends_on:
      - gene_search
      - chromosome_search
      - chromosome_region
    ports:
      - "8080:8080"
    environment:
#     GRPC_VERBOSITY: 'debug'
#     GRPC_TRACE: 'all'
      HTTP_HOST: "0.0.0.0"
      GENE_SEARCH_ADDR: gene_search:8081
      CHROMOSOME_SEARCH_ADDR: chromosome_search:8081
      CHROMOSOME_REGION_ADDR: chromosome_region:8081
    command:
      - --no-grpc

volumes:
  postgres-sock:
