version: '2.4'

services:
  client:
    build: 
      context: client
      target: dev
    ports:
      - "4200:4200"
    volumes:
      - /client/node_modules
      - ./client/src:/client/src:ro

  server:
    build:
      context: server
      target: dev
    environment:
      ALLOWED_HOSTS: '*'
      DEBUG: '1'
      PGDATABASE: postgres
      PGHOST: db
      PGNAME: postgres
      PGPASSWORD: postgres
      PGPORT: 5432
      PGUSER: postgres
      SECRET_KEY: secret_key
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app:ro

  db:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: "pg_isready -U postgres -h 127.0.0.1 || exit 1"
      retries: 10
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
